(*| PostgreSQL DDL generator for borge DB specs.

    Walks the typed DB AST and produces a complete SQL file
    with CREATE TABLE, CREATE INDEX, and RLS policy statements.
    See db.borg section convention-targets / postgres-sql-target for
    the full mapping specification. |*)

open Db_ast

(* --- Helper: SQL identifier escaping --- *)

(* exempt doc: trivial SQL id quote - name is self-documenting *)
let sql_id name =
  (* Quote identifiers that might collide with SQL keywords *)
  let need_quote = String.length name = 0 ||
    let c = name.[0] in not ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c = '_') in
  if need_quote then Printf.sprintf "\"%s\"" name
  else name

(* --- Helper: default value expression --- *)

let default_expr expr =
  match String.lowercase_ascii expr with
  | "gen_random_uuid" -> "gen_random_uuid()"
  | "now" -> "now()"
  | "false" -> "FALSE"
  | "true" -> "TRUE"
  | _ -> expr

(* --- Helper: column constraint to SQL --- *)

let column_constraint_to_sql = function
  | Primary_key -> "PRIMARY KEY"
  | Unique -> "UNIQUE"
  | Not_null -> "NOT NULL"
  | Default expr -> Printf.sprintf "DEFAULT %s" (default_expr expr)
  | References ref ->
    (* Parse table.column format *)
    match String.split_on_char '.' ref with
    | [table; col] ->
      Printf.sprintf "REFERENCES %s (%s)" (sql_id table) (sql_id col)
    | _ ->
      Printf.sprintf "REFERENCES %s" (sql_id ref)

(* --- Helper: column to SQL line --- *)

let column_to_sql (c : column) =
  let constraints = List.filter_map (function
    | Primary_key | Unique | Not_null | Default _ | References _ as cc ->
      Some (column_constraint_to_sql cc)
  ) c.constraints in
  let parts = [String.uppercase_ascii (sql_id c.typ)] @ constraints in
  Printf.sprintf "  %s %s" (sql_id c.name) (String.concat " " parts)

(* --- Helper: index method to SQL --- *)

let index_method_to_sql = function
  | Btree -> "btree"
  | Gin -> "gin"
  | Gist -> "gist"
  | Hash -> "hash"
  | Spgist -> "spgist"
  | Brin -> "brin"

(* --- Topological sort for foreign key dependencies --- *)

(*| Build a dependency graph from (references) constraints.
    Returns tables in an order where no table is created before
    the table it references. Circular references are an error. |*)

type dep_graph = (string, string list) Hashtbl.t

let build_dep_graph (tables : table_def list) =
  let graph : dep_graph = Hashtbl.create 16 in
  List.iter (fun (tbl : table_def) -> Hashtbl.add graph tbl.name []) tables;
  List.iter (fun (t : table_def) ->
    List.iter (fun (c : column) ->
      List.iter (function
        | References ref ->
          (match String.split_on_char '.' ref with
           | [dep_table; _] ->
             (* t.name depends on dep_table *)
             let deps = match Hashtbl.find_opt graph t.name with Some v -> v | None -> [] in
             if not (List.mem dep_table deps) then
               Hashtbl.replace graph t.name (dep_table :: deps)
           | _ -> ())
        | _ -> ())
      c.constraints
    ) t.columns
  ) tables;
  graph

let topological_sort (tables : table_def list) =
  let table_map = Hashtbl.create 16 in
  List.iter (fun (tbl : table_def) -> Hashtbl.add table_map tbl.name tbl) tables;
  let graph = build_dep_graph tables in
  let visited = Hashtbl.create 16 in
  let in_stack = Hashtbl.create 16 in
  let result = ref [] in
  let rec visit name =
    if Hashtbl.mem in_stack name then
      failwith (Printf.sprintf "Circular foreign key dependency involving table %s" name);
    if Hashtbl.mem visited name then ()
    else begin
      Hashtbl.add in_stack name ();
      let deps = match Hashtbl.find_opt graph name with Some v -> v | None -> [] in
      List.iter visit deps;
      Hashtbl.remove in_stack name;
      Hashtbl.add visited name ();
      (match Hashtbl.find_opt table_map name with
       | Some t -> result := t :: !result
       | None -> ())
    end
  in
  List.iter (fun (tbl : table_def) -> visit tbl.name) tables;
  List.rev !result

(* --- Schema header --- *)

let schema_header source_path =
  let timestamp =
    let t = Unix.time () in
    let tm = Unix.gmtime t in
    Printf.sprintf "%04d-%02d-%02dT%02d:%02d:%02dZ"
      (tm.Unix.tm_year + 1900) tm.Unix.tm_mon tm.Unix.tm_mday
      tm.Unix.tm_hour tm.Unix.tm_min tm.Unix.tm_sec
  in
  Printf.sprintf
    "-- Generated by borge generate --target postgres-sql\n\
     -- Source: %s\n\
     -- Generated at: %s\n\
     -- DO NOT EDIT: regenerate from spec\n"
    source_path timestamp

(* --- CREATE TABLE generation --- *)

let generate_table (t : table_def) =
  let cols = List.map column_to_sql t.columns in
  let col_list = String.concat ",\n" cols in
  Printf.sprintf "CREATE TABLE IF NOT EXISTS %s (\n%s\n);\n"
    (sql_id t.name) col_list

(* --- CREATE INDEX generation --- *)

let generate_index (table_name : string) (idx : index_def) =
  let col_list = String.concat ", " (List.map sql_id idx.columns) in
  let method_clause = match idx.idx_method with
    | Some m -> Printf.sprintf " USING %s" (index_method_to_sql m)
    | None -> ""
  in
  let unique_clause = if idx.unique then "UNIQUE " else "" in
  Printf.sprintf "CREATE %sINDEX IF NOT EXISTS %s ON %s%s (%s);\n"
    unique_clause (sql_id idx.name) (sql_id table_name) method_clause col_list

(* --- RLS: ownership shorthand policies --- *)

let generate_ownership_policies (t : table_def) =
  match t.ownership with
  | None -> ""
  | Some col ->
    let enable = Printf.sprintf "ALTER TABLE %s ENABLE ROW LEVEL SECURITY;\n" (sql_id t.name) in
    let ops = [
      ("SELECT", "USING");
      ("INSERT", "WITH CHECK");
      ("UPDATE", "USING");
      ("DELETE", "USING");
    ] in
    let policies = List.map (fun (op, _clause_type) ->
      let using_or_check =
        match op with
        | "UPDATE" ->
          Printf.sprintf "  FOR %s USING (%s = current_user_id())\n  WITH CHECK (%s = current_user_id())"
            op (sql_id col) (sql_id col)
        | "SELECT" | "DELETE" ->
          Printf.sprintf "  FOR %s USING (%s = current_user_id())"
            op (sql_id col)
        | "INSERT" ->
          Printf.sprintf "  FOR %s WITH CHECK (%s = current_user_id())"
            op (sql_id col)
        | _ -> ""
      in
      Printf.sprintf "CREATE POLICY %s_%s_%s ON %s\n%s;"
        (String.lowercase_ascii t.name) (sql_id col) (String.lowercase_ascii op)
        (sql_id t.name) using_or_check
    ) ops in
    enable ^ String.concat "\n" policies ^ "\n"

(* --- RLS: group policies --- *)

let operation_to_sql = function
  | "create" -> "INSERT"
  | "read" -> "SELECT"
  | "update" -> "UPDATE"
  | "delete" -> "DELETE"
  | op -> String.uppercase_ascii op

let where_clause_to_sql (w : string) =
  (* Replace current-user with current_user_id()
     and convert hyphens to underscores for SQL column names *)
  let w = String.map (fun c -> if c = '-' then '_' else c) w in
  let needle = "current_user" in
  let needle_len = String.length needle in
  let replacement = "current_user_id()" in
  let buf = Buffer.create (String.length w + 20) in
  let i = ref 0 in
  while !i <= String.length w - needle_len do
    if (* exempt: String.sub *) String.sub w !i needle_len = needle then begin
      Buffer.add_string buf replacement;
      i := !i + needle_len
    end else begin
      Buffer.add_char buf w.[!i];
      incr i
    end
  done;
  (* Copy remaining characters *)
  while !i < String.length w do
    Buffer.add_char buf w.[!i];
    incr i
  done;
  Buffer.contents buf

let generate_capability_policies (group_name : string) (cap : capability) =
  let table = sql_id cap.table in
  let gn = String.lowercase_ascii group_name in
  let tn = String.lowercase_ascii cap.table in
  List.map (fun op ->
    let sql_op = operation_to_sql op in
    let policy_name = Printf.sprintf "%s_%s_%s" gn tn (String.lowercase_ascii sql_op) in
    match op, cap.where_clause with
    | "read", Some w ->
      Printf.sprintf "CREATE POLICY %s ON %s FOR %s\n  USING (%s);"
        policy_name table sql_op (where_clause_to_sql w)
    | "create", Some w ->
      Printf.sprintf "CREATE POLICY %s ON %s FOR %s\n  WITH CHECK (%s);"
        policy_name table sql_op (where_clause_to_sql w)
    | "update", Some w ->
      Printf.sprintf "CREATE POLICY %s ON %s FOR %s\n  USING (%s)\n  WITH CHECK (%s);"
        policy_name table sql_op (where_clause_to_sql w) (where_clause_to_sql w)
    | "delete", Some w ->
      Printf.sprintf "CREATE POLICY %s ON %s FOR %s\n  USING (%s);"
        policy_name table sql_op (where_clause_to_sql w)
    | _, Some w ->
      Printf.sprintf "CREATE POLICY %s ON %s FOR %s\n  USING (%s);"
        policy_name table sql_op (where_clause_to_sql w)
    | _, None ->
      Printf.sprintf "CREATE POLICY %s ON %s FOR %s\n  USING (true);"
        policy_name table sql_op
  ) cap.operations

let generate_group_policies (g : group_def) =
  if g.can_all then
    (* can-all: single policy for ALL operations with USING (true) *)
    [Printf.sprintf "CREATE POLICY %s_all ON %%s FOR ALL\n  USING (true) WITH CHECK (true);"
       (String.lowercase_ascii g.name)]
    (* Note: table name needs to be filled in per-table. *)
    (* This is handled below in generate_groups *)
  else
    List.concat_map (generate_capability_policies g.name) g.capabilities

(* --- Operations/queries as comments --- *)

let generate_operations_comments (ops : operations_def) =
  let buf = Buffer.create 128 in
  (match ops.crud with
  | Some _ ->
    Buffer.add_string buf (Printf.sprintf "-- Operations on %s: CRUD" ops.table_name)
  | None -> ());
  List.iter (fun q ->
    let limit_str = match q.limit with Some n -> Printf.sprintf " (limit %d)" n | None -> "" in
    Buffer.add_string buf (Printf.sprintf "\n-- Query: %s%s for table %s"
      (String.lowercase_ascii q.name) limit_str (String.lowercase_ascii ops.table_name))
  ) ops.queries;
  Buffer.contents buf

(* --- Relations as comments --- *)

let generate_relation_comment (r : relation_def) =
  let joins = List.map (fun j ->
    let jt = match j.join_type with Inner_join -> "JOIN" | Left_join -> "LEFT JOIN" in
    Printf.sprintf "%s %s ON %s" jt (String.lowercase_ascii j.table) j.on_condition
  ) r.joins in
  let where_str = match r.where_clause with Some w -> Printf.sprintf "\n--   WHERE %s" w | None -> "" in
  let select_str = String.concat ", " (List.map String.lowercase_ascii r.select_columns) in
  Printf.sprintf "-- Relation: %s\n--   FROM %s %s%s\n--   SELECT %s"
    (String.lowercase_ascii r.name) (String.lowercase_ascii r.from_table)
    (String.concat " " joins) where_str select_str

(* --- Main generation --- *)

let generate ?(source_path = "<spec>") (app : db_app) =
  let buf = Buffer.create 4096 in

  (* Header *)
  Buffer.add_string buf (schema_header source_path);

  (* 1. CREATE TABLE statements (topologically sorted) *)
  let sorted_tables = topological_sort app.tables in
  Buffer.add_string buf "\n-- Tables\n\n";
  List.iter (fun (tbl : table_def) ->
    Buffer.add_string buf (generate_table tbl);
    Buffer.add_char buf '\n';
    (* Indexes for this table *)
    List.iter (fun idx ->
      Buffer.add_string buf (generate_index tbl.name idx)
    ) tbl.indexes;
    if tbl.indexes <> [] then Buffer.add_char buf '\n';
  ) sorted_tables;

  (* 2. RLS: ownership policies *)
  let tables_with_ownership = List.filter (fun (tbl : table_def) -> tbl.ownership <> None) sorted_tables in
  let tables_with_groups =
    if app.groups = [] then []
    else
      (* All tables that have group policies need RLS enabled *)
      let referenced = List.concat_map (fun g ->
        if g.can_all then []
        else List.map (fun c -> c.table) g.capabilities
      ) app.groups in
      List.filter (fun (tbl : table_def) -> List.mem tbl.name referenced) sorted_tables
  in
  let tables_needing_rls =
    List.filter (fun (tbl : table_def) ->
      tbl.ownership <> None ||
      List.exists (fun (tg : table_def) -> tg.name = tbl.name) tables_with_groups
    ) sorted_tables
  in
  if tables_needing_rls <> [] then begin
    Buffer.add_string buf "\n-- Row-Level Security\n\n";
    List.iter (fun (tbl : table_def) ->
      Buffer.add_string buf (generate_ownership_policies tbl);
      Buffer.add_char buf '\n';
    ) tables_with_ownership;

    (* 3. Group policies *)
    List.iter (fun (g : group_def) ->
      if g.can_all then (
        (* can-all needs to be per-table *)
        List.iter (fun (tbl : table_def) ->
          let policy = Printf.sprintf "CREATE POLICY %s_all ON %s FOR ALL\n  USING (true) WITH CHECK (true);\n"
            (String.lowercase_ascii g.name) (sql_id tbl.name) in
          Buffer.add_string buf policy
        ) sorted_tables;
        Buffer.add_char buf '\n';
      ) else
        List.iter (fun p ->
          Buffer.add_string buf p;
          Buffer.add_char buf '\n';
        ) (generate_group_policies g);
    ) app.groups;
  end;

  (* 4. Operations/queries as comments *)
  if app.operations <> [] then begin
    Buffer.add_string buf "\n-- Operations & Queries\n\n";
    List.iter (fun ops ->
      let comment = generate_operations_comments ops in
      if comment <> "" then
        Buffer.add_string buf (comment ^ "\n\n")
    ) app.operations;
  end;

  (* 5. Relations as comments *)
  if app.relations <> [] then begin
    Buffer.add_string buf "\n-- Relations\n\n";
    List.iter (fun r ->
      Buffer.add_string buf (generate_relation_comment r);
      Buffer.add_string buf "\n\n";
    ) app.relations;
  end;

  Buffer.contents buf
