(test
  (name test_parse)
  (libraries borge.lang borge.lib alcotest))

(test
  (name test_balance)
  (libraries borge.lang alcotest))

(test
  (name test_dune)
  (libraries borge.lang borge.lib alcotest))

(test
  (name test_meta)
  (libraries borge.lib alcotest))
(test
  (name test_ui_db)
  (libraries borge.lang borge.lib alcotest))
(test
  (name test_review)
  (libraries borge.lang borge.lib alcotest))
