(* Test ui_dream generator *)
open Borge_lib

let contains haystack needle =
  (* exempt: Str.search_forward *)
  try let _ = Str.search_forward (Str.regexp_string needle) haystack 0 in true
  with Not_found -> false

let test_simple_element () =
  let open Ui_ast in
  let app = {
    theme = None;
    components = [];
    layouts = [];
    pages = [];
    routes = [];
    elements = [
      { name = Some "box";
        properties = [P_layout Vertical; P_width (Flex 1); P_bg (Hex "#333")];
        children = [];
        variants = []; text = None;
      };
    ];
  } in
  let ml = Ui_dream.generate ~source_path:"test.borg" app in
  Alcotest.(check bool) "contains flex-col" true (contains ml "flex-col");
  Alcotest.(check bool) "contains flex: 1" true (contains ml "flex: 1");
  Alcotest.(check bool) "contains background-color" true (contains ml "background-color");
  Alcotest.(check bool) "contains header" true (contains ml "Generated by borge generate")

let test_theme_resolution () =
  let open Ui_ast in
  let app = {
    theme = Some { entries = [
      Palette_entry ("bg-primary", "#e0d7d2");
      Spacing_entry ("md", 16);
      Font_size_entry ("lg", 18);
      Radius_entry ("sm", 4);
    ] };
    components = [];
    layouts = [];
    pages = [];
    routes = [];
    elements = [
      { name = Some "box";
        properties = [P_bg (Palette "bg-primary"); P_padding (Padding_uniform (Spacing_var "md"))];
        children = [];
        variants = []; text = None;
      };
    ];
  } in
  let ml = Ui_dream.generate ~source_path:"test.borg" app in
  Alcotest.(check bool) "palette resolved to hex" true (contains ml "#e0d7d2");
  Alcotest.(check bool) "spacing resolved" true (contains ml "16px");
  Alcotest.(check bool) "contains CSS vars" true (contains ml "--bg-primary")

let test_component () =
  let open Ui_ast in
  let app = {
    theme = None;
    components = [
      { name = "button";
        properties = [P_interactive Interactive_click; P_padding (Padding_uniform (Spacing_px 8))];
        slots = [Default_slot];
        children = [];
        variants = [];
      };
    ];
    layouts = [];
    pages = [];
    routes = [];
    elements = [];
  } in
  let ml = Ui_dream.generate ~source_path:"test.borg" app in
  Alcotest.(check bool) "contains render_button" true (contains ml "render_button");
  Alcotest.(check bool) "contains click handler" true (contains ml "onclick")

let test_routes () =
  let open Ui_ast in
  let app = {
    theme = None;
    components = [];
    layouts = [];
    pages = [];
    routes = [{ path = "/"; page_name = "home" }; { path = "/dashboard"; page_name = "dashboard" }];
    elements = [];
  } in
  let ml = Ui_dream.generate ~source_path:"test.borg" app in
  Alcotest.(check bool) "contains Dream.get" true (contains ml "Dream.get");
  Alcotest.(check bool) "contains register_routes" true (contains ml "register_routes");
  Alcotest.(check bool) "contains / route" true (contains ml "\"/\"")
;;


let test_variant_media_queries () =
  let open Ui_ast in
  let app = {
    theme = None;
    components = [];
    layouts = [];
    pages = [];
    routes = [];
    elements = [
      { name = Some "sidebar";
        properties = [P_layout Vertical; P_width (Flex 1); P_padding (Padding_uniform (Spacing_px 16))];
        children = [];
        variants = [
          { name = "wide";
            properties = [P_layout Vertical; P_width (Flex 1); P_height Grow];
            children = None };
          { name = "narrow";
            properties = [P_layout Horizontal; P_width Full; P_height Auto];
            children = None };
        ];
        text = None;
      };
    ];
  } in
  let ml = Ui_dream.generate ~source_path:"test.borg" app in
  Alcotest.(check bool) "contains variant_css" true (contains ml "variant_css");
  Alcotest.(check bool) "contains @media" true (contains ml "@media");
  Alcotest.(check bool) "contains min-width: 768px" true (contains ml "min-width: 768px")

let test_style_merging () =
  let open Ui_ast in
  let app = {
    theme = None;
    components = [];
    layouts = [];
    pages = [];
    routes = [];
    elements = [
      { name = Some "box";
        properties = [P_bg (Hex "#333"); P_padding (Padding_uniform (Spacing_px 16)); P_gap (Spacing_px 8)];
        children = [];
        variants = []; text = None;
      };
    ];
  } in
  let ml = Ui_dream.generate ~source_path:"test.borg" app in
  (* All three CSS properties should be in a single a_style attribute *)
  Alcotest.(check bool) "contains background-color" true (contains ml "background-color");
  Alcotest.(check bool) "contains padding" true (contains ml "padding");
  Alcotest.(check bool) "contains gap" true (contains ml "gap")
;;

let () =
  Alcotest.run "ui_dream" [
    "ui_dream", [
      Alcotest.test_case "simple element" `Quick test_simple_element;
      Alcotest.test_case "theme resolution" `Quick test_theme_resolution;
      Alcotest.test_case "component" `Quick test_component;
      Alcotest.test_case "routes" `Quick test_routes;
      Alcotest.test_case "variant media queries" `Quick test_variant_media_queries;
      Alcotest.test_case "style merging" `Quick test_style_merging;
    ];
  ]
