(* Test db_sql generator *)
open Borge_lib

(* Helper: check if string contains substring *)
let contains haystack needle =
  try let _ = Str.search_forward (Str.regexp_string needle) haystack 0 in true
  with Not_found -> false

(* Helper: find position of substring *)
let find_pos haystack needle =
  try Str.search_forward (Str.regexp_string needle) haystack 0
  with Not_found -> -1

let test_simple_table () =
  let open Db_ast in
  let app = {
    tables = [
      { name = "users";
        columns = [
          { name = "id"; typ = "uuid"; constraints = [Primary_key; Default "gen_random_uuid"] };
          { name = "email"; typ = "text"; constraints = [Unique; Not_null] };
          { name = "created_at"; typ = "timestamptz"; constraints = [Default "now"] };
        ];
        indexes = [{ name = "email_idx"; columns = ["email"]; idx_method = None; unique = false }];
        ownership = None;
      };
    ];
    operations = [];
    relations = [];
    groups = [];
  } in
  let sql = Db_sql.generate ~source_path:"test.borg" app in
  Alcotest.(check bool) "contains CREATE TABLE" true (contains sql "CREATE TABLE IF NOT EXISTS users");
  Alcotest.(check bool) "contains uuid type" true (contains sql "UUID");
  Alcotest.(check bool) "contains PRIMARY KEY" true (contains sql "PRIMARY KEY");
  Alcotest.(check bool) "contains NOT NULL" true (contains sql "NOT NULL");
  Alcotest.(check bool) "contains gen_random_uuid()" true (contains sql "gen_random_uuid()");
  Alcotest.(check bool) "contains UNIQUE" true (contains sql "UNIQUE");
  Alcotest.(check bool) "contains CREATE INDEX" true (contains sql "CREATE INDEX IF NOT EXISTS email_idx");
  Alcotest.(check bool) "contains schema header" true (contains sql "Generated by borge generate")

let test_foreign_key_ordering () =
  let open Db_ast in
  let app = {
    tables = [
      (* posts references users — must come after users *)
      { name = "posts";
        columns = [
          { name = "id"; typ = "uuid"; constraints = [Primary_key] };
          { name = "author_id"; typ = "uuid"; constraints = [References "users.id"] };
        ];
        indexes = [];
        ownership = None;
      };
      { name = "users";
        columns = [
          { name = "id"; typ = "uuid"; constraints = [Primary_key] };
        ];
        indexes = [];
        ownership = None;
      };
    ];
    operations = [];
    relations = [];
    groups = [];
  } in
  let sql = Db_sql.generate ~source_path:"test.borg" app in
  let users_pos = find_pos sql "CREATE TABLE IF NOT EXISTS users" in
  let posts_pos = find_pos sql "CREATE TABLE IF NOT EXISTS posts" in
  Alcotest.(check bool) "users before posts" true (users_pos < posts_pos)

let test_ownership_rls () =
  let open Db_ast in
  let app = {
    tables = [
      { name = "posts";
        columns = [
          { name = "id"; typ = "uuid"; constraints = [Primary_key] };
          { name = "author_id"; typ = "uuid"; constraints = [Not_null] };
        ];
        indexes = [];
        ownership = Some "author_id";
      };
    ];
    operations = [];
    relations = [];
    groups = [];
  } in
  let sql = Db_sql.generate ~source_path:"test.borg" app in
  Alcotest.(check bool) "contains ENABLE ROW LEVEL SECURITY" true (contains sql "ENABLE ROW LEVEL SECURITY");
  Alcotest.(check bool) "contains SELECT policy" true (contains sql "FOR SELECT USING");
  Alcotest.(check bool) "contains INSERT policy" true (contains sql "FOR INSERT WITH CHECK");
  Alcotest.(check bool) "contains UPDATE policy" true (contains sql "FOR UPDATE USING");
  Alcotest.(check bool) "contains DELETE policy" true (contains sql "FOR DELETE USING");
  Alcotest.(check bool) "contains current_user_id()" true (contains sql "current_user_id()")

let test_group_policies () =
  let open Db_ast in
  let app = {
    tables = [
      { name = "posts";
        columns = [
          { name = "id"; typ = "uuid"; constraints = [Primary_key] };
          { name = "author_id"; typ = "uuid"; constraints = [Not_null] };
          { name = "published"; typ = "boolean"; constraints = [] };
        ];
        indexes = [];
        ownership = None;
      };
    ];
    operations = [];
    relations = [];
    groups = [
      { name = "admin"; can_all = true; capabilities = [] };
      { name = "reader";
        can_all = false;
        capabilities = [
          { table = "posts"; operations = ["read"]; where_clause = Some "published = true" };
        ];
      };
    ];
  } in
  let sql = Db_sql.generate ~source_path:"test.borg" app in
  Alcotest.(check bool) "contains admin can-all policy" true (contains sql "admin_all");
  Alcotest.(check bool) "admin USING true" true (contains sql "USING (true) WITH CHECK (true)");
  Alcotest.(check bool) "reader SELECT policy" true (contains sql "reader_posts_select");
  Alcotest.(check bool) "reader where published = true" true (contains sql "published = true")

let test_operations_as_comments () =
  let open Db_ast in
  let app = {
    tables = [
      { name = "users";
        columns = [{ name = "id"; typ = "uuid"; constraints = [Primary_key] }];
        indexes = [];
        ownership = None;
      };
    ];
    operations = [
      { table_name = "users"; crud = Some Crud_all; queries = [{ name = "by_email"; limit = None }] };
    ];
    relations = [];
    groups = [];
  } in
  let sql = Db_sql.generate ~source_path:"test.borg" app in
  Alcotest.(check bool) "contains operations comment" true (contains sql "-- Operations on users");
  Alcotest.(check bool) "contains query comment" true (contains sql "-- Query: by_email")

let test_relations_as_comments () =
  let open Db_ast in
  let app = {
    tables = [
      { name = "users";
        columns = [{ name = "id"; typ = "uuid"; constraints = [Primary_key] }];
        indexes = [];
        ownership = None;
      };
      { name = "posts";
        columns = [
          { name = "id"; typ = "uuid"; constraints = [Primary_key] };
          { name = "author_id"; typ = "uuid"; constraints = [References "users.id"] };
        ];
        indexes = [];
        ownership = None;
      };
    ];
    operations = [];
    relations = [
      { name = "user_posts";
        from_table = "users";
        joins = [{ join_type = Inner_join; table = "posts"; on_condition = "posts.author_id = users.id" }];
        where_clause = None;
        select_columns = ["users.name"; "posts.title"];
        queries = [];
      };
    ];
    groups = [];
  } in
  let sql = Db_sql.generate ~source_path:"test.borg" app in
  Alcotest.(check bool) "contains relation comment" true (contains sql "-- Relation: user_posts")
;;

let () =
  Alcotest.run "db_sql" [
    "db_sql", [
      Alcotest.test_case "simple table" `Quick test_simple_table;
      Alcotest.test_case "foreign key ordering" `Quick test_foreign_key_ordering;
      Alcotest.test_case "ownership RLS" `Quick test_ownership_rls;
      Alcotest.test_case "group policies" `Quick test_group_policies;
      Alcotest.test_case "operations as comments" `Quick test_operations_as_comments;
      Alcotest.test_case "relations as comments" `Quick test_relations_as_comments;
    ];
  ]
