(* Test ui_clay generator *)
open Borge_lib

let contains haystack needle =
  (* exempt: Str.search_forward *)
  try let _ = Str.search_forward (Str.regexp_string needle) haystack 0 in true
  with Not_found -> false

let test_simple_element () =
  let open Ui_ast in
  let app = {
    theme = None;
    components = [];
    layouts = [];
    pages = [];
    routes = [];
    elements = [
      { name = Some "box";
        properties = [P_layout Vertical; P_width (Flex 1); P_bg (Hex "#333")];
        children = [];
        variants = []; text = None;
      };
    ];
  } in
  let c = Ui_clay.generate ~source_path:"test.borg" app in
  Alcotest.(check bool) "contains CLAY_CONTAINER" true (contains c "CLAY_CONTAINER");
  Alcotest.(check bool) "contains TOP_TO_BOTTOM" true (contains c "CLAY_TOP_TO_BOTTOM");
  Alcotest.(check bool) "contains SIZING_GROW" true (contains c "CLAY_SIZING_GROW");
  Alcotest.(check bool) "contains background RGBA" true (contains c "backgroundColor");
  Alcotest.(check bool) "contains header" true (contains c "Generated by borge generate")

let test_color_rgba () =
  let open Ui_ast in
  let app = {
    theme = None;
    components = [];
    layouts = [];
    pages = [];
    routes = [];
    elements = [
      { name = Some "box";
        properties = [P_bg (Hex "#e0d7d2")];
        children = [];
        variants = []; text = None;
      };
    ];
  } in
  let c = Ui_clay.generate ~source_path:"test.borg" app in
  Alcotest.(check bool) "hex to RGBA" true (contains c "224, 215, 210, 255")

let test_keyword_color () =
  let open Ui_ast in
  let app = {
    theme = None;
    components = [];
    layouts = [];
    pages = [];
    routes = [];
    elements = [
      { name = Some "box";
        properties = [P_bg (Keyword "dark")];
        children = [];
        variants = []; text = None;
      };
    ];
  } in
  let c = Ui_clay.generate ~source_path:"test.borg" app in
  Alcotest.(check bool) "keyword dark RGBA" true (contains c "40, 40, 40, 255")

let test_c_sanitization () =
  let open Ui_ast in
  let app = {
    theme = None;
    components = [];
    layouts = [];
    pages = [];
    routes = [];
    elements = [
      { name = Some "nav-bar";
        properties = [P_layout Horizontal];
        children = [];
        variants = []; text = None;
      };
    ];
  } in
  let c = Ui_clay.generate ~source_path:"test.borg" app in
  Alcotest.(check bool) "hyphen to underscore" true (contains c "nav_bar")

let test_routes_enum () =
  let open Ui_ast in
  let app = {
    theme = None;
    components = [];
    layouts = [];
    pages = [];
    routes = [{ path = "/"; page_name = "home" }; { path = "/dashboard"; page_name = "dashboard" }];
    elements = [];
  } in
  let c = Ui_clay.generate ~source_path:"test.borg" app in
  Alcotest.(check bool) "contains enum page" true (contains c "enum page");
  Alcotest.(check bool) "contains PAGE_HOME" true (contains c "PAGE_HOME");
  Alcotest.(check bool) "contains layout_app switch" true (contains c "layout_app")

let test_header_file () =
  let open Ui_ast in
  let app = {
    theme = None;
    components = [{ name = "button"; properties = [P_interactive Interactive_click]; slots = []; children = []; variants = [] }];
    layouts = [];
    pages = [];
    routes = [{ path = "/"; page_name = "home" }];
    elements = [];
  } in
  let h = Ui_clay.generate_header_file app in
  Alcotest.(check bool) "contains include guard" true (contains h "#ifndef UI_APP_H");
  Alcotest.(check bool) "contains render_button declaration" true (contains h "render_button");
  Alcotest.(check bool) "contains enum page" true (contains h "enum page")
;;

let () =
  Alcotest.run "ui_clay" [
    "ui_clay", [
      Alcotest.test_case "simple element" `Quick test_simple_element;
      Alcotest.test_case "color RGBA" `Quick test_color_rgba;
      Alcotest.test_case "keyword color" `Quick test_keyword_color;
      Alcotest.test_case "C sanitization" `Quick test_c_sanitization;
      Alcotest.test_case "routes enum" `Quick test_routes_enum;
      Alcotest.test_case "header file" `Quick test_header_file;
    ];
  ]
