
(* Auto-generated by borge proof_emit. Do not edit by hand.
   This is the representation file a witness (.v) is checked against.
   Regenerate with: borge proof emit --spec DB_SPEC.borg

   Per docs/engine.borg subsection `obligations`: borge records what
   was claimed and binds it to a commit. This file is the machine-
   readable form of the spec a proof was discharged against. *)
From Stdlib Require Import String.
Open Scope string_scope.

Inductive operation : Type :=
  | Create | Read | Update | Delete.

Inductive table : Type :=
  | Users
  | Projects
  | Tasks
  | Comments.

Inductive column_of : table -> Type :=
  | Col_users_id : column_of (Users)
  | Col_users_email : column_of (Users)
  | Col_users_display_name : column_of (Users)
  | Col_users_role : column_of (Users)
  | Col_users_created_at : column_of (Users)
  | Col_projects_id : column_of (Projects)
  | Col_projects_name : column_of (Projects)
  | Col_projects_description : column_of (Projects)
  | Col_projects_owner_id : column_of (Projects)
  | Col_projects_created_at : column_of (Projects)
  | Col_tasks_id : column_of (Tasks)
  | Col_tasks_title : column_of (Tasks)
  | Col_tasks_description : column_of (Tasks)
  | Col_tasks_status : column_of (Tasks)
  | Col_tasks_priority : column_of (Tasks)
  | Col_tasks_project_id : column_of (Tasks)
  | Col_tasks_assignee_id : column_of (Tasks)
  | Col_tasks_due_date : column_of (Tasks)
  | Col_tasks_created_at : column_of (Tasks)
  | Col_comments_id : column_of (Comments)
  | Col_comments_body : column_of (Comments)
  | Col_comments_task_id : column_of (Comments)
  | Col_comments_author_id : column_of (Comments)
  | Col_comments_created_at : column_of (Comments).

Definition owner_of (t : table) : option string :=
  match t with
  | Users => None
  | Projects => Some "owner-id"
  | Tasks => Some "assignee-id"
  | Comments => Some "author-id"
  end.

Inductive group : Type :=
  | Admin
  | Member
  | Viewer.

Inductive is_admin : group -> Prop :=
  | is_admin_Admin : is_admin Admin.

Inductive permitted : group -> operation -> table -> Prop :=
  | permitted_Member_Create_Tasks : permitted Member Create Tasks
  | permitted_Member_Read_Tasks : permitted Member Read Tasks
  | permitted_Member_Update_Tasks : permitted Member Update Tasks
  | permitted_Member_Read_Projects : permitted Member Read Projects
  | permitted_Member_Create_Comments : permitted Member Create Comments
  | permitted_Member_Read_Comments : permitted Member Read Comments
  | permitted_Viewer_Read_Tasks : permitted Viewer Read Tasks
  | permitted_Viewer_Read_Projects : permitted Viewer Read Projects
  | permitted_Viewer_Read_Comments : permitted Viewer Read Comments.

Definition predicate_column_of (g : group) (op : operation) (t : table) : option string :=
  match g, op, t with
  | Member, Create, Tasks => Some "assignee-id"
  | Member, Read, Tasks => Some "assignee-id"
  | Member, Update, Tasks => Some "assignee-id"
  | Member, Read, Projects => None
  | Member, Create, Comments => None
  | Member, Read, Comments => None
  | Viewer, Read, Tasks => None
  | Viewer, Read, Projects => None
  | Viewer, Read, Comments => None
  | _, _, _ => None
  end.

