/* --- ui_app.h --- */
/* Generated by borge generate --target clay-c */
/* DO NOT EDIT: regenerate from spec */

#ifndef UI_APP_H
#define UI_APP_H

#include "clay.h"

enum page {
  PAGE_PROJECTS,
  PAGE_TASKS,
  PAGE_TASK_DETAIL
};

extern enum page current_page;

Clay_Children render_button(void);
Clay_Children render_card(void);
Clay_Children render_input_field(void);
Clay_Children render_nav_item(void);
void layout_app_shell(int screen_width, int screen_height);
void layout_sidebar_layout(int screen_width, int screen_height);
void layout_page_projects(int screen_width, int screen_height);
void layout_page_tasks(int screen_width, int screen_height);
void layout_page_task_detail(int screen_width, int screen_height);
void layout_app(int screen_width, int screen_height);

#endif /* UI_APP_H */

/* --- ui_app.c --- */
/* Generated by borge generate --target clay-c */
/* Source: examples/crud-app/ui.borg */
/* DO NOT EDIT: regenerate from spec */

#include "ui_app.h"

enum page current_page = PAGE_PROJECTS;

/* Interactive handlers — fill in actual behavior */

void handle_button_hover(Clay_HoverState state) {
  /* TODO: implement click/hover for button */
}

void handle_input_field_hover(Clay_HoverState state) {
  /* TODO: implement click/hover for input-field */
}

void handle_nav_item_hover(Clay_HoverState state) {
  /* TODO: implement click/hover for nav-item */
}

/* Components */

Clay_Children render_button(void) {
  return (Clay_Children){
    CLAY_CONTAINER(CLAY_IDI(button), CLAY_LAYOUT_CONFIG({
      .cornerRadius = { 6, 6, 6, 6 },
      .backgroundColor = { 59, 130, 246, 255 }
      .onHover = handle_button_hover,
    }), {
    });
  };
}

Clay_Children render_card(void) {
  return (Clay_Children){
    CLAY_CONTAINER(CLAY_IDI(card), CLAY_LAYOUT_CONFIG({
      .padding = { 16, 16, 16, 16 },
      .cornerRadius = { 8, 8, 8, 8 },
      .backgroundColor = { 255, 255, 255, 255 }
    }), {
    });
  };
}

Clay_Children render_input_field(void) {
  return (Clay_Children){
    CLAY_CONTAINER(CLAY_IDI(input_field), CLAY_LAYOUT_CONFIG({
      .cornerRadius = { 6, 6, 6, 6 },
      .backgroundColor = { 255, 255, 255, 255 },
      .sizing.width = CLAY_SIZING_PERCENT(1.0f)
      .onHover = handle_input_field_hover,
    }), {
    });
  };
}

Clay_Children render_nav_item(void) {
  return (Clay_Children){
    CLAY_CONTAINER(CLAY_IDI(nav_item), CLAY_LAYOUT_CONFIG({
      .cornerRadius = { 4, 4, 4, 4 }
      .onHover = handle_nav_item_hover,
    }), {
    });
  };
}

/* Layouts */

void layout_app_shell(int screen_width, int screen_height) {
    CLAY_CONTAINER(CLAY_IDI(root), CLAY_LAYOUT_CONFIG({
      .layoutDirection = CLAY_LEFT_TO_RIGHT,
      .sizing.width = CLAY_SIZING_PERCENT(1.0f),
      .sizing.height = CLAY_SIZING_PERCENT(1.0f)
    }), {
        CLAY_CONTAINER(CLAY_IDI(sidebar), CLAY_LAYOUT_CONFIG({
          .layoutDirection = CLAY_TOP_TO_BOTTOM,
          .sizing.width = { CLAY_SIZING_FIXED(240), CLAY_SIZING_FIXED(240) },
          .sizing.height = CLAY_SIZING_PERCENT(1.0f),
          .backgroundColor = { 30, 41, 59, 255 },
          .padding = { 16, 16, 16, 16 },
          .childGap = 8
        }), {
        });
        CLAY_CONTAINER(CLAY_IDI(main), CLAY_LAYOUT_CONFIG({
          .layoutDirection = CLAY_TOP_TO_BOTTOM,
          .sizing.width = { CLAY_SIZING_GROW(0), CLAY_SIZING_GROW(0) },
          .sizing.height = CLAY_SIZING_PERCENT(1.0f),
          .backgroundColor = { 248, 249, 250, 255 },
          .padding = { 24, 24, 24, 24 },
          .childGap = 16,
          .scroll = { .vertical = true }
        }), {
        });
    });
}

void layout_sidebar_layout(int screen_width, int screen_height) {
    CLAY_CONTAINER(CLAY_IDI(root), CLAY_LAYOUT_CONFIG({
      .layoutDirection = CLAY_TOP_TO_BOTTOM,
      .sizing.width = CLAY_SIZING_PERCENT(1.0f),
      .sizing.height = CLAY_SIZING_PERCENT(1.0f),
      .backgroundColor = { 30, 41, 59, 255 },
      .padding = { 16, 16, 16, 16 },
      .childGap = 8
    }), {
        CLAY_CONTAINER(CLAY_IDI(brand), CLAY_LAYOUT_CONFIG({
          .padding = { 16, 16, 16, 16 }
        }), {
        });
        CLAY_CONTAINER(CLAY_IDI(nav), CLAY_LAYOUT_CONFIG({
          
        }), {
        });
        CLAY_CONTAINER(CLAY_IDI(spacer), CLAY_LAYOUT_CONFIG({
          .sizing.height = { CLAY_SIZING_GROW(0), CLAY_SIZING_GROW(0) }
        }), {
        });
        CLAY_CONTAINER(CLAY_IDI(user_section), CLAY_LAYOUT_CONFIG({
          .padding = { 16, 16, 16, 16 }
        }), {
        });
    });
}

/* Pages */

void layout_page_projects(int screen_width, int screen_height) {
  /* FILL: nav */
  /* FILL: content */
  layout_app_shell(screen_width, screen_height);
}

void layout_page_tasks(int screen_width, int screen_height) {
  /* FILL: nav */
  /* FILL: content */
  layout_app_shell(screen_width, screen_height);
}

void layout_page_task_detail(int screen_width, int screen_height) {
  /* FILL: nav */
  /* FILL: content */
  layout_app_shell(screen_width, screen_height);
}

/* Route dispatcher */

void layout_app(int screen_width, int screen_height) {
  switch (current_page) {
    case PAGE_PROJECTS: layout_page_projects(screen_width, screen_height); break;
    case PAGE_TASKS: layout_page_tasks(screen_width, screen_height); break;
    case PAGE_TASK_DETAIL: layout_page_task_detail(screen_width, screen_height); break;
  }
}

