(* Generated by borge generate --target ocaml-dream *)
(* Source: examples/crud-app/ui.borg *)
(* DO NOT EDIT: regenerate from spec *)

open Dream_html

let theme_css = "<style>\n:root {\n  --success: #22c55e;\n  --danger: #ef4444;\n  --border: #e2e8f0;\n  --accent-hover: #2563eb;\n  --bg-sidebar: #1e293b;\n  --accent: #3b82f6;\n  --bg: #f8f9fa;\n  --text-primary: #1e293b;\n  --bg-surface: #ffffff;\n  --text-inverse: #ffffff;\n  --text-secondary: #64748b;\n  --spacing-lg: 24px;\n  --spacing-md: 16px;\n  --spacing-xl: 32px;\n  --spacing-sm: 8px;\n  --spacing-xs: 4px;\n  --font-size-base: 14px;\n  --font-size-lg: 18px;\n  --font-size-xl: 24px;\n  --font-size-sm: 12px;\n  --radius-lg: 8px;\n  --radius-md: 6px;\n  --radius-sm: 4px;\n}\n</style>\n"

(* Variant media queries *)

let variant_css = "@media (max-width: 767px) {\n  .button.variant-danger { background-color: #ef4444 }\n}\n\n@media (max-width: 767px) {\n  .button.variant-outline { background-color: #ffffff; color: #3b82f6 }\n}\n\n@media (max-width: 767px) {\n  .nav_item.variant-active { background-color: #3b82f6 }\n}\n"

(* Components *)

let render_button ~(content : Html.node list) () : Html.node =
  Html.div ~a:[Html.a_style "background-color: #3b82f6; border-radius: 6px; color: #ffffff"; Html.a_on_click (fun _ -> Dream.redirect "TODO")] []

let render_card ~(content : Html.node list) () : Html.node =
  Html.div ~a:[Html.a_style "background-color: #ffffff; border-radius: 8px; padding: 16px"] []

let render_input_field ~(content : Html.node list) () : Html.node =
  Html.div ~a:[Html.a_style "background-color: #ffffff; border-radius: 6px; width: 100%"; Html.a_on_click (fun _ -> Dream.redirect "TODO")] []

let render_nav_item ~(content : Html.node list) () : Html.node =
  Html.div ~a:[Html.a_style "border-radius: 4px; color: #ffffff"; Html.a_on_click (fun _ -> Dream.redirect "TODO")] []

(* Layouts *)

let render_app_shell_layout ~(content : Html.node list) () : Html.node =
  Html.div ~a:[Html.a_class ["flex-row"]; Html.a_style "height: 100%; width: 100%"] [Html.div ~a:[Html.a_class ["flex-col"]; Html.a_style "background-color: #1e293b; gap: 8px; height: 100%; padding: 16px; width: 240px"] []; Html.div ~a:[Html.a_class ["flex-col"]; Html.a_style "background-color: #f8f9fa; flex: 1 1 0%; gap: 16px; height: 100%; overflow-y: auto; padding: 24px"] []]

let render_sidebar_layout_layout ~(content : Html.node list) () : Html.node =
  Html.div ~a:[Html.a_class ["flex-col"]; Html.a_style "background-color: #1e293b; gap: 8px; height: 100%; padding: 16px; width: 100%"] [Html.div ~a:[Html.a_style "padding: 16px"] []; Html.div [] []; Html.div ~a:[Html.a_style "flex: 1 1 0%"] []; Html.div ~a:[Html.a_style "color: #ffffff; padding: 16px"] []]

(* Pages *)

let render_projects () : Html.node =
  render_app_shell_layout ~content:[; ] ()

let render_tasks () : Html.node =
  render_app_shell_layout ~content:[; ] ()

let render_task_detail () : Html.node =
  render_app_shell_layout ~content:[; ] ()

(* Routes *)

let register_routes () = Dream.router [
  Dream.get "/" (fun _ -> Dream_html.respond (render_projects ()));
  Dream.get "/tasks" (fun _ -> Dream_html.respond (render_tasks ()));
  Dream.get "/tasks/:id" (fun _ -> Dream_html.respond (render_task_detail ()));
]

